notify = [ "C:\\Users\\DATARPE\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\1b23c930bdf84ed6\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]


model_catalog_json = "C:\\Users\\DATARPE\\.codex\\ollama-launch-models.json"

[windows]
sandbox = "unelevated"

[marketplaces.openai-bundled]
last_updated = "2026-07-05T10:28:32Z"
source_type = "local"
source = '\\?\C:\Users\DATARPE\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-03T23:05:20Z"
source_type = "local"
source = '\\?\C:\Users\DATARPE\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[projects.'c:\users\datarpe\desktop\smartfinance']
trust_level = "trusted"

[projects.'c:\users\datarpe\desktop\forge']
trust_level = "trusted"

[projects.'c:\users\datarpe\desktop\smartfinance_new_ui\smartfinance']
trust_level = "trusted"

[desktop]
followUpQueueMode = "queue"
conversationDetailMode = "STEPS_COMMANDS"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = 'C:\Users\DATARPE\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\DATARPE\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\DATARPE\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\DATARPE\.codex'
CODEX_HOME = 'C:\Users\DATARPE\.codex'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "566be6ef352eb3de899adc56a9cd7b5e46c8f65b00e56b5630dd7a580e10cbea,60e4902788f207f88fd09344dfeafe07769488bdb2924bbb12b322c3b9d2b999"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.101652"
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-6cf4b933-f48a-4cdc-9ef2-e8453193688b'
CODEX_CLI_PATH = 'C:\Users\DATARPE\AppData\Local\OpenAI\Codex\bin\ea1c60319a1dcb19\codex.exe'

[model_providers.ollama-launch-codex-app]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1/"
wire_api = "responses"
