-- ============================================================
-- Fixes to revert_monthly_budget_month
-- ============================================================
-- Redefines revert_monthly_budget_month() (20260901002200_revert_monthly_budget_month.sql)
-- in place -- same signature, same grants, no trigger/table changes
-- needed. Two real bugs and one unhandled edge case found while
-- reviewing the "reset the whole month" flow against its own stated
-- goal ("the selected month should behave as if the Monthly Budget had
-- never been executed"):
--
-- 1. is_overridden was never cleared. materialize_planned_item_occurrences'
--    upsert (see 20260901001800_planned_item_rpcs.sql, function #1) only
--    ever refreshes a row when `status = 'planned' and not is_overridden`
--    -- the ON CONFLICT ... WHERE guard silently no-ops otherwise. The
--    original revert reset `status` back to 'planned' but left
--    `is_overridden` untouched, so any occurrence a user had
--    hand-overridden before confirming stayed stuck on its old (possibly
--    exactly the wrong values the user is trying to fix) snapshot
--    forever -- the next preview/materialize call for that month would
--    silently skip re-resolving it. This directly breaks the user's
--    stated scenario ("I configured something incorrectly ... fix the
--    configuration ... run the month again from scratch"): fixing the
--    underlying planned_items definition would never reach an
--    already-overridden occurrence. Fixed by clearing is_overridden in
--    the same UPDATE that resets status.
--
-- 2. 'skipped'/'cancelled' occurrences were left untouched. Only
--    status = 'confirmed' was reset -- but skip_planned_item_occurrence
--    and cancel_planned_item_occurrence (20260901001800_planned_item_rpcs.sql,
--    functions #6) are both reachable before a month is committed, and
--    neither status implies a generated transaction exists (both
--    require status = 'planned' to begin with, same precondition
--    confirm_planned_item_month itself never overrides). Leaving them
--    'skipped'/'cancelled' after a full-month reset means they are
--    *not* "as if the Monthly Budget had never been executed" -- the
--    materialize upsert guard above skips non-'planned' rows regardless
--    of *why* they're non-'planned', so a skipped/cancelled item stays
--    permanently excluded from every future run of that month, with no
--    way back short of deleting and recreating the occurrence by hand.
--    Fixed by folding 'skipped'/'cancelled' into the same reset as
--    'confirmed'. 'matched' occurrences are deliberately NOT included
--    here -- see the note below, this is unchanged from the original.
--
-- 3. No guard against transactions.id being referenced by
--    replenishment_run_transactions.transaction_id, which is
--    `on delete restrict` (20260901000000_replenishment_schema.sql). A
--    Monthly-Budget-generated expense transaction (plain_expense role)
--    can legitimately be picked up later by the separate Replenishment
--    ("Reposição") feature as one of the original expenses a run repays.
--    If that happens, the unguarded DELETE below raised a raw Postgres
--    foreign-key-violation error -- the whole call still rolled back
--    atomically (ordinary Postgres function/transaction semantics, no
--    partial state), but the household admin got an opaque low-level
--    error with no indication of what to do about it. Fixed by checking
--    for this up front and raising a clear, actionable message instead.
--    This is a real interaction between two features that both reference
--    `transactions` with different lifecycle assumptions (Monthly
--    Budget expects to be able to delete/regenerate its own transactions
--    freely; Replenishment expects the expenses it repays to be stable
--    history) -- if this turns out to happen often in practice, the
--    cleaner long-term fix is probably to change
--    replenishment_run_transactions.transaction_id to `on delete cascade`
--    (dropping the replenishment run's line for that expense along with
--    the expense itself) or `on delete set null` (keeping the run's
--    snapshot row but marking it orphaned) rather than leaning on a
--    guard that just blocks the reset outright -- deliberately not
--    changed here, since that is a product decision about what should
--    happen to a replenishment run when one of its expenses disappears,
--    not just a bug fix.
--
-- Unchanged from the original: still deletes only transactions carrying
-- planned_item_occurrence_id (safe by construction -- see the original
-- migration's comment), still leaves 'matched' occurrences and the real
-- transactions they point at completely alone (a matched transaction was
-- manually entered/matched, never generated by confirm_planned_item_month
-- -- see match_planned_item_occurrence's own comment -- so it is exactly
-- the "manually created transactions will not be affected" case the
-- confirmation dialog promises), still reopens monthly_budget_periods,
-- and still runs as a single atomic call (one plpgsql function body is
-- one implicit transaction -- any exception anywhere above, including
-- the new guard, rolls back everything, so this can never leave deleted
-- transactions with a still-committed period, a half-reset occurrence
-- set, or any other inconsistent mix).

create or replace function public.revert_monthly_budget_month(
    p_household_id uuid,
    p_month date
)
returns public.monthly_budget_periods
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_period public.monthly_budget_periods%rowtype;
    v_blocked_count integer;
begin
    if not public.is_household_admin(p_household_id, auth.uid()) then
        raise exception 'Only household admins can revert a monthly budget month';
    end if;

    -- Fail fast with a clear message instead of an opaque FK-violation
    -- error (replenishment_run_transactions.transaction_id is
    -- `on delete restrict`) if any transaction this call is about to
    -- delete has since been picked up by a Replenishment run.
    select count(*) into v_blocked_count
      from public.transactions t
      join public.replenishment_run_transactions rrt on rrt.transaction_id = t.id
     where t.household_id = p_household_id
       and t.planned_item_occurrence_id in (
             select id
               from public.planned_item_occurrences
              where household_id = p_household_id
                and month = p_month
           );

    if v_blocked_count > 0 then
        raise exception 'Cannot reset Monthly Budget for %: % transaction(s) generated for this month are referenced by a Replenishment (Reposição) run. Remove them from that run first, then try again.',
            to_char(p_month, 'YYYY-MM'), v_blocked_count;
    end if;

    delete from public.transactions
     where household_id = p_household_id
       and planned_item_occurrence_id in (
             select id
               from public.planned_item_occurrences
              where household_id = p_household_id
                and month = p_month
           );

    -- Reset every occurrence a confirm/skip/cancel could have moved out
    -- of 'planned' for this month back to 'planned', and clear
    -- is_overridden so a fresh materialize call is free to re-resolve it
    -- from the (possibly just-fixed) planned_items definition. 'matched'
    -- occurrences are deliberately excluded -- see the migration header.
    update public.planned_item_occurrences
       set status = 'planned',
           confirmed_at = null,
           confirmed_by = null,
           is_overridden = false
     where household_id = p_household_id
       and month = p_month
       and status in ('confirmed', 'skipped', 'cancelled');

    update public.monthly_budget_periods
       set status = 'open',
           confirmed_at = null,
           confirmed_by = null
     where household_id = p_household_id
       and month = p_month
     returning * into v_period;

    if v_period.id is null then
        -- Nothing to reopen -- the month was never committed in the
        -- first place. Report its current (or default 'open', absent)
        -- state rather than erroring, same "no-op is fine" spirit as
        -- confirm_planned_item_month's own already-committed handling.
        select * into v_period
          from public.monthly_budget_periods
         where household_id = p_household_id
           and month = p_month;
    end if;

    return v_period;
end;
$$;

comment on function public.revert_monthly_budget_month(uuid, date) is
  'Deletes every transaction confirm_planned_item_month generated for this household+month, resets their occurrences (confirmed/skipped/cancelled -> planned, is_overridden cleared) back to plannable, and reopens the monthly_budget_periods row. Never touches a hand-entered or matched transaction. Raises a clear error instead of a raw FK violation if a generated transaction is referenced by a Replenishment run. See 20260901002300_revert_monthly_budget_month_fixes.sql for what changed from the original 20260901002200 version and why.';

revoke all on function public.revert_monthly_budget_month(uuid, date) from public;
grant execute on function public.revert_monthly_budget_month(uuid, date) to authenticated;
