import { StyleSheet } from "react-native";

import { radius } from "@/theme/radius";
import { spacing } from "@/theme/spacing";
import { typography } from "@/theme/typography";

type SafeAreaInsets = { top: number; bottom: number; left: number; right: number };

const NO_INSETS: SafeAreaInsets = { top: 0, bottom: 0, left: 0, right: 0 };

// `insets` defaults to zero so any other caller that doesn't pass device
// insets still gets the previous, non-safe-area-aware layout rather than
// breaking. transactions.tsx passes the real useSafeAreaInsets() result so
// the floating create button and the modal backdrops here clear the iOS
// home indicator / Android system nav bar instead of sitting under them.
export function createStyles(colors: any, insets: SafeAreaInsets = NO_INSETS) {
  return StyleSheet.create({
    viewTabs: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: spacing(2),
      padding: spacing(2),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceMuted,
    },
    sectionActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: spacing(2),
    },
    bulkActionBar: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "flex-end",
      gap: spacing(3),
      padding: spacing(3),
      marginBottom: spacing(3),
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: radius.lg,
      backgroundColor: colors.primarySoft,
    },
    bulkActionSummary: {
      minWidth: spacing(44),
      flex: 1,
      gap: spacing(1),
      alignSelf: "center",
    },
    bulkActionTitle: {
      color: colors.text,
      fontSize: typography.fontSize[16],
      fontWeight: String(typography.fontWeight.extraBold),
    },
    bulkActionHint: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
    },
    bulkCategoryField: {
      minWidth: spacing(52),
      flexGrow: 1,
    },
    bulkCheckbox: {
      width: spacing(9),
      height: spacing(9),
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.full,
      backgroundColor: colors.surface,
    },
    bulkCheckboxSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    bulkCheckboxDisabled: {
      opacity: 0.38,
    },
    transactionHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: spacing(3),
    },
    transactionIdentity: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(2),
    },
    transactionIcon: {
      width: spacing(9),
      height: spacing(9),
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    transactionDetails: { flex: 1, gap: spacing(0.5) },
    transactionTitle: {
      color: colors.text,
      fontWeight: String(typography.fontWeight.bold),
    },
    transactionAccount: {
      color: colors.text,
      fontWeight: String(typography.fontWeight.semibold),
    },
    transactionCreator: {
      color: colors.primary,
      fontWeight: String(typography.fontWeight.bold),
    },
    transactionContext: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
    },
    transactionAmount: {
      fontSize: typography.fontSize[16],
      fontWeight: String(typography.fontWeight.extraBold),
    },
    transactionBalance: {
      color: colors.text,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.bold),
    },
    personIdentity: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
    },
    menuButton: {
      width: spacing(10.5),
      height: spacing(10.5),
      borderRadius: radius.mdPlus,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    menuButtonText: {
      color: colors.text,
      fontSize: typography.fontSize[22],
      fontWeight: String(typography.fontWeight.extraBold),
      lineHeight: typography.lineHeight[22],
    },
    floatingCreateButton: {
      position: "absolute",
      right: spacing(6),
      bottom: spacing(6) + insets.bottom,
      zIndex: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing(2),
      paddingHorizontal: spacing(4),
      paddingVertical: spacing(3),
      borderRadius: radius.full,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    floatingCreateButtonText: {
      color: colors.primaryForeground,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.extraBold),
    },
    floatingCreateSpacer: {
      height: spacing(16) + insets.bottom,
    },
    filterToggle: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      borderWidth: 1,
      borderRadius: radius.lg,
      paddingHorizontal: spacing(3),
      paddingVertical: spacing(2),
    },
    filterToggleLabel: {
      fontSize: typography.fontSize[13],
      fontWeight: typography.fontWeight.semibold as any,
    },
    filtersGrid: {
      width: "100%",
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "flex-start",
      gap: spacing(3),
    },
    filterGridItem: {
      minWidth: 0,
      alignSelf: "stretch",
    },
    filterChoiceGroup: {
      gap: spacing(2),
      padding: spacing(3),
      borderWidth: 1,
      borderRadius: radius.lg,
    },
    filterGroupLabel: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
    },
    filterGroupLabelText: {
      fontSize: typography.fontSize[13],
      fontWeight: typography.fontWeight.semibold as any,
    },
    filterPills: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: spacing(2),
    },
    filterRangeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing(2),
      width: "100%",
    },
    activeFiltersRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: spacing(2),
      marginBottom: spacing(3),
    },
    alwaysVisibleSearchRow: {
      marginBottom: spacing(3),
    },
    activeFilterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      paddingHorizontal: spacing(3),
      paddingVertical: spacing(1.5),
      borderRadius: radius.full,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
    },
    activeFilterChipText: {
      fontSize: typography.fontSize[12],
      fontWeight: typography.fontWeight.semibold as any,
      color: colors.text,
    },
    clearAllButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      paddingHorizontal: spacing(3),
      paddingVertical: spacing(1.5),
      borderRadius: radius.full,
      borderWidth: 1,
      borderColor: colors.destructive,
    },
    clearAllButtonText: {
      fontSize: typography.fontSize[12],
      fontWeight: typography.fontWeight.semibold as any,
      color: colors.destructive,
    },
    summaryBar: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "stretch",
      gap: spacing(3),
      marginBottom: spacing(4),
    },
    summaryBarItem: {
      flexGrow: 1,
      minWidth: spacing(32),
      gap: spacing(1),
      padding: spacing(3.5),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceMuted,
    },
    summaryBarLabel: {
      fontSize: typography.fontSize[12],
      fontWeight: typography.fontWeight.semibold as any,
      color: colors.textSecondary,
    },
    summaryBarValue: {
      fontSize: typography.fontSize[18],
      fontWeight: typography.fontWeight.extraBold as any,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "center",
      padding: spacing(5),
      paddingTop: spacing(5) + insets.top,
      paddingBottom: spacing(5) + insets.bottom,
      backgroundColor: "rgba(2, 6, 23, 0.82)",
    },
    modalKeyboardView: {
      width: "100%",
      maxHeight: "92%",
      alignSelf: "center",
    },
    createModalCard: {
      width: "100%",
      maxWidth: spacing(190),
      maxHeight: "100%",
      alignSelf: "center",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.xl,
      backgroundColor: colors.surface,
    },
    createModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(3),
      paddingHorizontal: spacing(5),
      paddingVertical: spacing(4),
      borderBottomWidth: 1,
    },
    modalIcon: {
      width: spacing(11),
      height: spacing(11),
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.lg,
    },
    modalHeading: {
      flex: 1,
      gap: spacing(0.5),
    },
    modalClose: {
      width: spacing(10),
      height: spacing(10),
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderRadius: radius.full,
    },
    modalPressed: {
      opacity: 0.72,
    },
    createModalScroll: {
      flexShrink: 1,
    },
    createModalBody: {
      gap: spacing(3.5),
      padding: spacing(5),
    },
    typeSelector: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      gap: spacing(2),
      padding: spacing(2),
      borderWidth: 1,
      borderRadius: radius.full,
    },
    formGrid: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: spacing(3),
    },
    formGridCompact: {
      flexDirection: "column",
    },
    formGridItem: {
      flex: 1,
      width: "100%",
      minWidth: 0,
    },
    createModalFooter: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing(2.5),
      paddingHorizontal: spacing(5),
      paddingVertical: spacing(3.5),
      borderTopWidth: 1,
      backgroundColor: colors.surface,
    },
    createModalPrimaryActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "flex-end",
      gap: spacing(2.5),
    },
    modalCard: {
      width: "100%",
      maxWidth: spacing(160),
      alignSelf: "center",
      gap: spacing(3.5),
      padding: spacing(4.5),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.xl,
      backgroundColor: colors.surface,
    },
    editModalCard: {
      maxHeight: "92%",
      padding: 0,
      overflow: "hidden",
    },
    editModalContent: {
      gap: spacing(3.5),
      padding: spacing(4.5),
    },
    menuCard: {
      width: "100%",
      maxWidth: spacing(96),
      alignSelf: "center",
      gap: spacing(3),
      padding: spacing(4.5),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.xl,
      backgroundColor: colors.surface,
    },
    modalTitle: {
      color: colors.text,
      fontSize: typography.fontSize[20],
      fontWeight: String(typography.fontWeight.extraBold),
    },
    modalSubtitle: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[13],
      lineHeight: typography.lineHeight[18],
    },
    wizardProgressTrack: {
      flexDirection: "row",
      gap: spacing(1.5),
    },
    wizardProgressSegment: {
      flex: 1,
      height: spacing(1),
      borderRadius: radius.full,
    },
    wizardStepHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing(2),
    },
    wizardBackButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1),
      alignSelf: "flex-start",
    },
    wizardBackLabel: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[13],
      fontWeight: typography.fontWeight.semibold as any,
    },
    wizardStepIndicator: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
      fontWeight: typography.fontWeight.bold as any,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    wizardStepTitle: {
      color: colors.text,
      fontSize: typography.fontSize[16],
      fontWeight: String(typography.fontWeight.extraBold),
    },
    wizardStepSubtitle: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[13],
      lineHeight: typography.lineHeight[18],
    },
    wizardStepBody: {
      gap: spacing(3.5),
    },
    editAttachmentsSection: {
      gap: spacing(2),
      padding: spacing(3),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceMuted,
    },
    editAttachmentsHeading: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
    },
    editAttachmentsTitle: {
      color: colors.text,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.bold),
    },
    editAttachmentsStatus: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[13],
    },
    editAttachmentsError: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing(2),
    },
    editAttachmentsList: { gap: spacing(3) },
    editAttachmentItem: { gap: spacing(1) },
    editAttachmentMeta: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
    },
    categorySuggestionStatus: {
      minHeight: spacing(4.5),
      justifyContent: "center",
    },
    categorySuggestionText: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
      lineHeight: typography.lineHeight[18],
    },
    titleSuggestionBox: {
      marginTop: spacing(1.5),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.lg,
      backgroundColor: colors.surface,
    },
    titleSuggestionRow: {
      gap: spacing(0.5),
      paddingHorizontal: spacing(3.5),
      paddingVertical: spacing(2.5),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    titleSuggestionRowActive: { backgroundColor: colors.primarySoft },
    titleSuggestionTitle: {
      color: colors.text,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.bold),
    },
    titleSuggestionContext: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
    },
    modalActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing(2.5),
      justifyContent: "flex-end",
    },
    menuItem: {
      paddingVertical: spacing(3.5),
      paddingHorizontal: spacing(3.5),
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
    },
    menuItemDanger: {
      paddingVertical: spacing(3.5),
      paddingHorizontal: spacing(3.5),
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: colors.destructiveBorder,
      backgroundColor: colors.destructiveSoft,
    },
    menuItemText: {
      color: colors.text,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.bold),
    },
    menuItemTextDanger: {
      color: colors.destructive,
      fontSize: typography.fontSize[14],
      fontWeight: String(typography.fontWeight.bold),
    },
    pressed: {
      opacity: 0.85,
    },
    splitBadgeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1),
      alignSelf: "flex-start",
      marginTop: spacing(0.5),
    },
    splitBreakdown: {
      width: "100%",
      alignSelf: "stretch",
      borderWidth: 1,
      borderRadius: radius.lg,
      padding: spacing(3),
      gap: spacing(2),
      marginTop: -spacing(1),
      marginBottom: spacing(2),
    },
    splitBreakdownHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1),
      flexWrap: "wrap",
    },
    splitBreakdownHeaderLabel: {
      color: colors.textSecondary,
      fontSize: typography.fontSize[12],
      fontWeight: String(typography.fontWeight.bold),
      textTransform: "uppercase",
    },
    splitBreakdownEntryRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(2),
      flexWrap: "wrap",
      paddingTop: spacing(1.5),
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
  } as any);
}
